```python
from pathlib import Path
from datetime import datetime
import sys

# ==========================================================
# Andaliman Specification Builder
# Sprint 01 - Bootstrap
# ==========================================================

ROOT = Path(__file__).resolve().parent.parent
SPECIFICATION_DIR = ROOT / "specification"
OUTPUT_DIR = ROOT / "output"
OUTPUT_FILE = OUTPUT_DIR / "andaliman_v1.md"

EXPECTED_FILES = [
    "01_constitution.md",
    "02_identity_governance_builder_protocol.md",
    "03_core_engine.md",
    "04_analysis_engine.md",
    "05_output_standard.md",
    "06_hmt_scope.md",
    "07_golden_test_suite.md",
    "08_adr_index.md",
    "09_master_prompt.md",
]


def print_banner():
    print("=" * 50)
    print("Andaliman Specification Builder")
    print("=" * 50)


def validate_specifications():
    missing = []

    for filename in EXPECTED_FILES:
        filepath = SPECIFICATION_DIR / filename

        if not filepath.exists():
            missing.append(filename)

    if missing:
        print("\nBuild Failed\n")

        for file in missing:
            print(f"Missing : {file}")

        sys.exit(1)


def load_specifications():
    documents = []

    for filename in EXPECTED_FILES:
        filepath = SPECIFICATION_DIR / filename

        content = filepath.read_text(
            encoding="utf-8"
        )

        documents.append(
            (filename, content)
        )

    return documents


def build_runtime(documents):

    OUTPUT_DIR.mkdir(exist_ok=True)

    runtime = []

    runtime.append("# ANDALIMAN CORE ENGINE\n")
    runtime.append("Generated Runtime Specification\n\n")
    runtime.append("Version : AS-1.0 Alpha\n")
    runtime.append("Generated by : Andaliman Specification Builder\n")
    runtime.append(
        f"Generated at : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
    )
    runtime.append("\n")
    runtime.append("DO NOT EDIT THIS FILE.\n")
    runtime.append(
        "This file is generated automatically.\n"
    )
    runtime.append("\n")
    runtime.append("=" * 60 + "\n")
    runtime.append("BEGIN CANONICAL SPECIFICATION\n")
    runtime.append("=" * 60 + "\n\n")

    for filename, content in documents:

        runtime.append("=" * 60 + "\n")
        runtime.append(f"{filename}\n")
        runtime.append("=" * 60 + "\n\n")

        runtime.append(content)
        runtime.append("\n\n")

    runtime.append("=" * 60 + "\n")
    runtime.append("END CANONICAL SPECIFICATION\n")
    runtime.append("=" * 60 + "\n")

    OUTPUT_FILE.write_text(
        "".join(runtime),
        encoding="utf-8"
    )


def build_report(documents):

    print("\n")
    print("=" * 50)
    print("Build Report")
    print("=" * 50)

    print(f"Loaded : {len(documents)} specifications")
    print(f"Output : {OUTPUT_FILE}")

    print("Status : SUCCESS")

    print("=" * 50)


def main():

    print_banner()

    validate_specifications()

    documents = load_specifications()

    build_runtime(documents)

    build_report(documents)


if __name__ == "__main__":
    main()
```
